// import Image from 'next/image'
"use client";

import { useListMeaningsQuery } from "@/domain/sentence/meaning.queries";

import { useUpdateComponentSummaryMutation } from "@/domain/component-summary/update-component-summary";
import { ListMeaningsResponse } from "@/domain/sentence/meanings.types";
import { useGetCharacterId } from "@/hooks/use-get-character-id";
import { useGetCurrentLang } from "@/hooks/use-get-current-lang";
import { useSearchParams } from "next/navigation";
import { Editor } from "../Editor";

import { Nothing } from "@/app/nmm/nothing";
import { useIsSuperAdmin } from "@/domain/auth/auth.queries";
import { create } from "zustand";
import { AnimatedLoadingText } from "../animated-loading-text";
import { Icons } from "../ui/icons.v2";
import { WithYoutubeVideo } from "./with-youtube-video";

export const useSummaryStore = create((set) => ({
  summary: "",
  setSummary: (id: string) => set(() => ({ summary: id })),
}));

export function Summary({
  characterId,
  showMeanings,
}: {
  characterId: string;
  showMeanings: boolean;
}) {
  const _characterId = useGetCharacterId();

  const lang = useGetCurrentLang();

  const updateSummaryMutation = useUpdateComponentSummaryMutation();

  const summary = useSummaryStore((state: any) => state.summary);
  const isSuperAdmin = useIsSuperAdmin();
  const searchParams = useSearchParams();

  const setSummary = useSummaryStore((state: any) => state.setSummary);
  const statusUrl = searchParams.get("status-url");

  const {
    data: meaningResponse,
    isLoading,
    isError,
  } = useListMeaningsQuery({
    content: _characterId,
    lang,
  });

  if (isLoading) {
    return (
      <div className="my-4">
        <AnimatedLoadingText
          className="text-xl font-bold"
          message="Generating summary..."
        />
      </div>
    );
  }

  if (isError) {
    return <Nothing message={"Error loading summary"} />;
  }

  return (
    <main className="dark:bg-[rgb(11,12,13)] bg-gray-50 p-2 rounded-2xl mt-4">
      <WithYoutubeVideo characterId={_characterId} lang={lang} />

      <div className="">
        <div className="">
          {meaningResponse?.summary && (
            <Editor
              readOnly={false}
              content={meaningResponse?.summary || summary}
              onUpdate={(val: any) => {
                // console.log("VAL", val);
                setSummary(val);
                // updateSummaryMutation.mutate
              }}
            />
          )}

          {isSuperAdmin &&
            Boolean(summary) &&
            JSON.stringify(summary) !==
              JSON.stringify(meaningResponse?.summary) && (
              <button
                className="my-12"
                onClick={() => {
                  return (
                    updateSummaryMutation
                      // @ts-ignore
                      .mutateAsync({
                        id: meaningResponse?.id,
                        summary,
                      })
                      .then(() => {
                        console.log("Summary Successfully Updated");
                      })
                  );
                }}
              >
                {updateSummaryMutation.isPending ? (
                  <Icons.spinner spinPulse />
                ) : false ? (
                  <Icons.checkCircle className="transition" />
                ) : (
                  "Save"
                )}
              </button>
            )}
        </div>
      </div>

      {isLoading ? null : (
        <p className="my-32 text-center text-gray-500">
          <strong> Note: </strong>The summary, audio and sentences above were
          generated by AI and may contain inaccuracies.
        </p>
      )}
    </main>
  );
}
