export const languages = [
  { id: "ar", label: "Arabic" },
  { id: "fa", label: "Persian" },
  { id: "ja", label: "Japanese" },
  { id: "ko", label: "Korean" },
  { id: "es", label: "Spanish" },
  { id: "fr", label: "French" },
  { id: "vi", label: "Vietnamese" },
  { id: "ur", label: "Urdu" },
  { id: "ru", label: "Russian" },
  { id: "ne", label: "Nepali" },
  { id: "ro", label: "Romanian" },
  { id: "da", label: "Danish" },
  { id: "no", label: "Norwegian" },
  { id: "hi", label: "Hindi" },
  { id: "ml", label: "Malayalam" },
];
