export const hindiAlphabets = [
  { en: "A", input: "अ", roman: "a", lang: "hi" },
  { en: "Aa", input: "आ", roman: "aa", lang: "hi" },
  { en: "I", input: "इ", roman: "i", lang: "hi" },
  { en: "Ii", input: "ई", roman: "ii", lang: "hi" },
  { en: "U", input: "उ", roman: "u", lang: "hi" },
  { en: "Uu", input: "ऊ", roman: "uu", lang: "hi" },
  { en: "Ri", input: "ऋ", roman: "ri", lang: "hi" },
  { en: "E", input: "ए", roman: "e", lang: "hi" },
  { en: "Ai", input: "ऐ", roman: "ai", lang: "hi" },
  { en: "O", input: "ओ", roman: "o", lang: "hi" },
  { en: "Au", input: "औ", roman: "au", lang: "hi" },
  { en: "Anusvara", input: "अं", roman: "an", lang: "hi" },
  { en: "Visarga", input: "अः", roman: "ah", lang: "hi" },

  { en: "Ka", input: "क", roman: "k", lang: "hi" },
  { en: "Kha", input: "ख", roman: "kh", lang: "hi" },
  { en: "Ga", input: "ग", roman: "g", lang: "hi" },
  { en: "Gha", input: "घ", roman: "gh", lang: "hi" },
  { en: "Nga", input: "ङ", roman: "ṅ", lang: "hi" },

  { en: "Cha", input: "च", roman: "ch", lang: "hi" },
  { en: "Chha", input: "छ", roman: "chh", lang: "hi" },
  { en: "Ja", input: "ज", roman: "j", lang: "hi" },
  { en: "Jha", input: "झ", roman: "jh", lang: "hi" },
  { en: "Nya", input: "ञ", roman: "ñ", lang: "hi" },

  { en: "Ta (retroflex)", input: "ट", roman: "ṭ", lang: "hi" },
  { en: "Tha (retroflex)", input: "ठ", roman: "ṭh", lang: "hi" },
  { en: "Da (retroflex)", input: "ड", roman: "ḍ", lang: "hi" },
  { en: "Dha (retroflex)", input: "ढ", roman: "ḍh", lang: "hi" },
  { en: "Na (retroflex)", input: "ण", roman: "ṇ", lang: "hi" },

  { en: "Ta (dental)", input: "त", roman: "t", lang: "hi" },
  { en: "Tha (dental)", input: "थ", roman: "th", lang: "hi" },
  { en: "Da (dental)", input: "द", roman: "d", lang: "hi" },
  { en: "Dha (dental)", input: "ध", roman: "dh", lang: "hi" },
  { en: "Na (dental)", input: "न", roman: "n", lang: "hi" },

  { en: "Pa", input: "प", roman: "p", lang: "hi" },
  { en: "Pha", input: "फ", roman: "ph", lang: "hi" },
  { en: "Ba", input: "ब", roman: "b", lang: "hi" },
  { en: "Bha", input: "भ", roman: "bh", lang: "hi" },
  { en: "Ma", input: "म", roman: "m", lang: "hi" },

  { en: "Ya", input: "य", roman: "y", lang: "hi" },
  { en: "Ra", input: "र", roman: "r", lang: "hi" },
  { en: "La", input: "ल", roman: "l", lang: "hi" },
  { en: "Va", input: "व", roman: "v", lang: "hi" },

  { en: "Sha", input: "श", roman: "ś", lang: "hi" },
  { en: "Sha (retroflex)", input: "ष", roman: "ṣ", lang: "hi" },
  { en: "Sa", input: "स", roman: "s", lang: "hi" },
  { en: "Ha", input: "ह", roman: "h", lang: "hi" },

  { en: "Ksha", input: "क्ष", roman: "kṣ", lang: "hi" },
  { en: "Tra", input: "त्र", roman: "tr", lang: "hi" },
  { en: "Gya", input: "ज्ञ", roman: "jñ", lang: "hi" },
];
